### ISSUE TITLE
TypeError: Private key not in range [1, n)

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#1017]
Using the current main (cb4c5f16a), it is not possible to start Station Desktop. I tried both `npm start` and `npm test`.

```
TypeError: Private key not in range [1, n)
at fromPrivateKeyLocal (/Users/bajtos/src/filstation/desktop/node_modules/@glif/filecoin-wallet-provider/node_modules/bip32/src/bip32.js:267:15)
at fromPrivateKey (/Users/bajtos/src/filstation/desktop/node_modules/@glif/filecoin-wallet-provider/node_modules/bip32/src/bip32.js:257:12)
at Object.fromSeed (/Users/bajtos/src/filstation/desktop/node_modules/@glif/filecoin-wallet-provider/node_modules/bip32/src/bip32.js:295:12)
at keyDeriveFromSeed (/Users/bajtos/src/filstation/desktop/node_modules/@glif/filecoin-wallet-provider/node_modules/@zondax/filecoin-signing-tools/js/src/index.js:28:27)
at Object.keyDerive (/Users/bajtos/src/filstation/desktop/node_modules/@glif/filecoin-wallet-provider/node_modules/@zondax/filecoin-signing-tools/js/src/index.js:46:10)
at _callee$ (/Users/bajtos/src/filstation/desktop/node_modules/@glif/filecoin-wallet-provider/dist/providers/hd-wallet-provider/index.js:112:42)
at tryCatch (/Users/bajtos/src/filstation/desktop/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
at Generator._invoke (/Users/bajtos/src/filstation/desktop/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
at Generator.next (/Users/bajtos/src/filstation/desktop/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
at asyncGeneratorStep (/Users/bajtos/src/filstation/desktop/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/Users/bajtos/src/filstation/desktop/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at /Users/bajtos/src/filstation/desktop/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
at new Promise (<anonymous>)
at HDWalletProvider.getAccounts (/Users/bajtos/src/filstation/desktop/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
at WalletBackend.getAddress (/Users/bajtos/src/filstation/desktop/main/wallet-backend.js:72:50)
at WalletBackend.setup (/Users/bajtos/src/filstation/desktop/main/wallet-backend.js:46:31)
```

<img width="588" alt="Screenshot 2023-10-10 at 11 33 24" src="https://github.com/filecoin-station/desktop/assets/1140553/94500a81-2fb8-491f-9a50-f99064901f0d">

<img width="328" alt="Screenshot 2023-10-10 at 11 35 16" src="https://github.com/filecoin-station/desktop/assets/1140553/7e3559e2-0577-4ed4-9e81-bbf14fee4748">

_Originally posted by @bajtos in https://github.com/filecoin-station/desktop/issues/1016#issuecomment-1754822583_

**Comment by juliangruber** [comment]
I can't reproduce, even after `rm -rf node_modules && npm install`. Can you please try to reproduce again?

**Comment by bajtos** [comment]
Thank you for checking! After running `rm -rf node_modules`, everything works fine for me too. Weird, isn't it?

I am closing this issue as invalid.

**Comment by juliangruber** [comment]
We you maybe manually checking one of the dependabot electron upgrade PRs?
