### ISSUE TITLE
Release builds are failing - WalletBackend.getMessages error 401

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#1756]
Release workflow run for 2.2.0:

https://github.com/filecoin-station/desktop/actions/runs/10244799174/job/28392989784

The error:

```
AssertionError [ERR_ASSERTION]: Could not fetch messages (Status 401)
    at /home/runner/work/desktop/desktop/main/wallet-backend.js:279:7
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async WalletBackend.getMessages (/home/runner/work/desktop/desktop/main/wallet-backend.js:270:22)
    at async WalletBackend.fetchAllTransactions (/home/runner/work/desktop/desktop/main/wallet-backend.js:300:22)
    at async RetryOperation._fn (file:///home/runner/work/desktop/desktop/node_modules/p-retry/index.js:57:20) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

Regular CI builds are not encountering this error.

I re-run the release workflow multiple times, but all re-runs failed on all platforms.

**Comment by juliangruber** [comment]
This is also frequently failing in regular CI, see https://github.com/filecoin-station/desktop/actions/runs/10350849747/job/28648119472

**Comment by juliangruber** [comment]
It probably is a expired Zondax token. Rotating

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/desktop/releases/tag/v2.2.1
